name: "nhom2_quanlynhahang"
version: "0.0.0"
description: "Ứng dụng quản lý nhà hàng - Nhóm 02 (Lập trình di động)."

publish_to: "none"

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
